# Server Port
server.port=8321

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/medicare_db_main?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=vinay@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Secret
jwt.secret=medicare-super-secret-key-must-be-32-chars-minimum-2024
jwt.expiration=86400000